name: 'Webform Demo: Application/Evaluation System'
type: module
description: 'Demonstrate how to use the Webform module to build an application/evaluation system.'
package: 'Webform Demo'
# core: 8.x
dependencies:
  - 'drupal:block'
  - 'webform:webform'

# Information added by Drupal.org packaging script on 2018-01-31
version: '8.x-5.0-rc2'
core: '8.x'
project: 'webform'
datestamp: 1517359392
