name: Environment indicator
type: module
description: Adds a color indicator for the different environments.
package: Development
# core: 8.x
dependencies:
  - drupal:color

scripts:
  - js/environment_indicator.js
  - js/color.js

stylesheets:
  all:
    - css/environment_indicator.css

configure: environment_indicator.settings

# Information added by Drupal.org packaging script on 2019-03-24
version: '8.x-3.6'
core: '8.x'
project: 'environment_indicator'
datestamp: 1553405888
